symbols:
  - internal: HK.00700
    futu: HK.00700
    ib_symbol: '700'
    ib_exchange: SEHK
    ib_currency: HKD
    market: HK
  - internal: US.AAPL
    futu: US.AAPL
    ib_symbol: AAPL
    ib_exchange: SMART
    ib_currency: USD
    market: US